### ISSUE TITLE
tiktok, ig, remini/hd eror

### ISSUE THREAD

**Issue by Kiznaiverr** [rifnd/moon-bot#13]
Remini :

TypeError: Cannot read properties of undefined (reading 'url')
    at Object.run (/home/container/plugins/tools/remini.js:38:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (/home/container/handler.js:320:19)

Tiktok :

TypeError: Cannot read properties of undefin ed (reading 'nickname')

at Object.run(/home/container/plugins/d

ownloader/tiktok.js:23:49)

at process.processTicksAndRejections (no de: internal/process/task_queues: 95:5)

at async Object.handler (/home/container

handler.js:320:19

Ig :
TypeError: json.data is not iterable
    at Object.run (/home/container/plugins/downloader/ig.js:22:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (/home/container/handler.js:320:19)

**Comment by Kiznaiverr** [comment]
Yyy
